<a href="<?=App::config('url')?>">predavac/novi"
class="sucsess button expanded">Dodaj novi</a>
<div class="grid-x grid padding-x">
        <?php foreach($eniteti as $e):?>
            <div class="large-3 cell">
            <div class="callout" style="text-align: center;">
                slika
                <hr />
                <h1 style="font-size: 1.5rem;"><?=$e->ime?> <?=$e->prezime?></h1>
                <?=$e->email?>, <?=$e->oib?>
                <hr />
                <a href="<?=App::config('url')?>predavac/promjena/<?=$e->sifra?>">
                    <i style="color: blue;" 
                    class="step fi-pencil size-36"></i>
                </a>
                <?php if($e->grupa==0):?>
                    <a href="<?=App::config('url')?>predavac/brisanje/<?=$e->sifra?>">
                        <i style="color: red;" 
                        class="step fi-page-delete size-36"></i>
                    </a>
                    <?php endif; ?>
                </div>
            </div>
            <?php endforeach ?>
    </div>
